name: autobrr
services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:v1.80.0@sha256:004fb15d02e77a6a2799e76798359a2152daae5f939f19412fba7d344e87e3b2
    network_mode: bridge
    restart: unless-stopped
    environment:
      TZ: $TZ
    ports:
      - target: 7474
        published: "7474"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
x-casaos:
  id: org.icewhale.autobrr
  main: autobrr
  port_map: "7474"
  title:
    en_US: Autobrr
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.autobrr/assets/icon.svg
  version: "1.79.0"
