name: gitea
services:
  gitea:
    environment:
      USER_GID: "1000"
      USER_UID: "1000"
    image: gitea/gitea:1.27.2@sha256:b67389c604243d96cbc9ba6be18b94e409eb40ceb05dbe61e39edd55b7ceb58a
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 3000
        published: "3002"
        protocol: tcp
      - target: 22
        published: "222"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    container_name: gitea
x-casaos:
  id: org.icewhale.gitea
  main: gitea
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.gitea/assets/icon.svg
  title:
    en_US: Gitea
  index: /
  port_map: "3002"
  version: "1.27.2"
