name: glances
services:
  glances:
    container_name: glances
    image: nicolargo/glances:4.5.6@sha256:f8ec00131bf5c0b375b9e02debbbc30d451eba7a63c33e3cbc510b8227ef4570
    pid: host
    deploy:
      resources:
        reservations:
          memory: "256M"
    environment:
      GLANCES_OPT: -w
      po: PO
    restart: unless-stopped
    network_mode: bridge
    privileged: false
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /mnt
        target: /mnt
      - type: bind
        source: /DATA
        target: /4nt
    ports:
      - target: 61208
        published: "61208"
        protocol: tcp
      - target: 61209
        published: "61209"
        protocol: tcp
      - target: 51209
        published: "51209"
        protocol: tcp

x-casaos:
  id: org.icewhale.glances
  main: glances
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.glances/assets/icon.svg
  title:
    en_US: Glances
    zh_CN: Glances
    pt_BR: Glances
  index: /
  port_map: "61208"
  version: "4.5.6"
