name: duckdns
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest@sha256:9daa778abcb2c96d15e9de1aed697f9a8175109d167d16c5f99be675811cb103
    container_name: duckdns
    network_mode: host #optional
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      - UPDATE_IP=ipv6 #optional
      - LOG_FILE=false #optional
    volumes:
      - /DATA/AppData/duckdns:/config #optional
    restart: unless-stopped

x-casaos:
  id: org.icewhale.duckdns
  main: duckdns
  icon: https://raw.githubusercontent.com/Doliopi/CasaOS-AppStore/refs/heads/gh-pages/apps/org.icewhale.duckdns/assets/icon.svg
  title:
    en_US: duckdns
  index: /
  version: "0.0.1"
