name: pihole
services:
  pihole:
    environment:
      TZ: 444
      FTLCONF_webserver_api_password: 444
      FTLCONF_dns_listeningMode: all
      gfv: ff
    image: pihole/pihole:2026.07.0@sha256:ee102b672a9722a48983d9d3a22a626fdb8de091a18a751273203f0e507f563a
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "8800"
        protocol: tcp
      - target: 53
        published: "7545"
        protocol: tcp
      - target: 466
        published: "53"
        protocol: udp
      - target: 443
        published: "8443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/etc/pihole/
        target: /etc/pihole
      - type: bind
        source: /DATA/ccccc
        target: /ccccc
    cap_add:
      - NET_ADMIN
    container_name: pihole
x-casaos:
  id: org.icewhale.pihole
  main: pihole
  icon: https://raw.githubusercontent.com/Doliopi/CasaOS-AppStore/refs/heads/gh-pages/apps/org.icewhale.pihole/assets/icon.svg
  title:
    en_US: Pi-hole
  index: /admin
  port_map: "8800"
  version: "2026.7.0"
