name: pihole
services:
  pihole:
    environment:
      TZ: $TZ
      FTLCONF_webserver_api_password: casaos
      FTLCONF_dns_listeningMode: all
      oo: oop
    image: pihole/pihole:2026.06.0@sha256:5c7011eb7f75c6ce62a55c9517a684fa530e7a5e31b28ef80f7a7b2f11e7375d
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "8800"
        protocol: tcp
      - target: 53
        published: "1113"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 443
        published: "8443"
        protocol: tcp
      - target: 566
        published: "6554"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/etc/pihole/
        target: /etc/pihole
      - type: bind
        source: /DATA/
        target: /ttt
    cap_add:
      - NET_ADMIN
    container_name: pihole
x-casaos:
  id: org.icewhale.pihole
  main: pihole
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.pihole/assets/icon.svg
  title:
    en_US: Pi-hole
  index: /admin
  port_map: "8800"
  version: "2026.6.0"
