name: pihole
services:
  pihole:
    environment:
      xg: 4441
      FTLCONF_webserver_api_password: 444
      gfv: ff
      aa: aa
    image: pihole/pihole:2026.07.2
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8044
        published: "18806"
        protocol: tcp
      - target: 53
        published: "7545"
        protocol: tcp
      - target: 443
        published: "8443"
        protocol: tcp
      - target: 41143
        published: "6443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/
        target: /etc/pihole1
      - type: bind
        source: /DATA/ccccc
        target: /ccccc
      - type: bind
        source: /DATA/zzz
        target: /zzzz
    cap_add:
      - NET_ADMIN
    container_name: pihole
x-casaos:
  id: org.icewhale.pihole
  main: pihole
  icon: https://raw.githubusercontent.com/Doliopi/CasaOS-AppStore/refs/heads/gh-pages/apps/org.icewhale.pihole/assets/icon.svg
  title:
    en_US: Pi-hole
  index: /admin
  port_map: "8800"
  version: "2026.7.2"
