name: pihole
services:
  pihole:
    environment:
      TZ: $TZ
      FTLCONF_webserver_api_password: casaos
      FTLCONF_dns_listeningMode: all
      oop: oo
    image: pihole/pihole:2026.07.1@sha256:45cf4d2f581a9bc9d3d4d89b3b88f23a601289644807dd99367566b7bb4cebd0
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "8800"
        protocol: tcp
      - target: 53
        published: "113"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 443
        published: "8443"
        protocol: tcp
      - target: 5443
        published: "18443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/etc/pihole/
        target: /etc/pihol
      - type: bind
        source: /DATA/343
        target: /etc
    cap_add:
      - NET_ADMIN
    container_name: pihole
x-casaos:
  id: org.icewhale.pihole
  main: pihole
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.pihole/assets/icon.svg
  title:
    en_US: Pi-hole
  index: /admin
  port_map: "8800"
  version: "2026.7.1"
