name: pyload
services:
  pyload:
    container_name: pyload
    image: linuxserver/pyload-ng:0.5.0@sha256:e9ab025ba654a40c79197f389d01f4f3a61dbc62a13eed8e887780af57b11d12
    deploy:
      resources:
        reservations:
          memory: "256M"
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    restart: unless-stopped
    network_mode: bridge
    privileged: false
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9666
        published: "9666"
        protocol: tcp

x-casaos:
  id: org.icewhale.pyload
  main: pyload
  icon: https://raw.githubusercontent.com/Doliopi/CasaOS-AppStore/refs/heads/gh-pages/apps/org.icewhale.pyload/assets/icon.svg
  title:
    en_US: PyLoad
    zh_CN: PyLoad
    pt_BR: PyLoad
  index: /
  port_map: "8000"
  version: "0.5.0"
