name: netbird
services:
  netbird:
    image: netbirdio/netbird:0.76.0
    container_name: netbird
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    deploy:
      resources:
        reservations:
          memory: 128M
    environment:
      NB_SETUP_KEY: "22"
      NB_MANAGEMENT_URL: "33"
      NB_HOSTNAME: "Zima"
      NB_ENABLE_SSH_ROOT: "true"
      NB_ALLOW_SERVER_SSH: "true"
      NB_ALLOW_SERVER_SSH1: "true"
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /var/lib/netbird
      - type: bind
        source: /DATA/5
        target: /var/5
x-casaos:
  id: org.icewhale.netbird
  main: netbird
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.netbird/assets/icon.svg
  scheme: "https"
  port_map: ""
  index: /
  title:
    en_US: NetBird
  version: "0.76.0"
