name: openlist
services:
  openlist:
    image: openlistteam/openlist:v4.2.3@sha256:100d9c322eab711a1c69228783d26f36c884bfff842303f4cf4d1f761bb0aa9e
    container_name: openlist
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    restart: unless-stopped
    user: "999:1000"
    ports:
      - target: 5244
        published: "5244"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /opt/openlist/data
    environment:
      UMASK: "022"
      OPENLIST_ADMIN_PASSWORD: "casaos"
x-casaos:
  id: org.icewhale.openlist
  main: openlist
  icon: https://cdn.jsdelivr.net/gh/Doliopi/CasaOS-AppStore@gh-pages/apps/org.icewhale.openlist/assets/icon.svg
  scheme: http
  port_map: "5244"
  index: /
  title:
    en_US: OpenList
  version: "4.2.3"
